(define (test -__Arg1 -__Arg2)
  (define (-__Func1)
    (let ((A -__Arg1))
      (if (equal? A -__Arg2)
        (begin
          (pretty-print "Correct: ")
          (pretty-print A)
          (pretty-print "")
          #t)
        (-__Func2))))
  (define (-__Func2)
    (let ((A -__Arg1))
      (let ((B -__Arg2))
        (begin
          (pretty-print "Wrong. Result: ")
          (pretty-print A)
          (pretty-print ". Correct: ")
          (pretty-print B)
          (pretty-print "")
          #f))))
  (-__Func1))
(define (upper-case? -__Arg1)
  (define (-__Func1)
    (let ((S -__Arg1))
      (if (member
            (car (string->list S))
            (string->list "ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
        #t
        #f)))
  (-__Func1))
(define (var? -__Arg1)
  (define (-__Func1)
    (let ((A -__Arg1))
      (and (symbol? A)
           (upper-case? (symbol->string A)))))
  (-__Func1))
(define (scheme-symbol? -__Arg1)
  (define (-__Func1)
    (let ((A -__Arg1))
      (and (symbol? A) (not (var? A)))))
  (-__Func1))
(define (with-clean-gensym -__Arg1)
  (define (-__Func1)
    (let ((A -__Arg1))
      (begin (set! *my-gensym-N* 0) (A))))
  (-__Func1))
(define (gensym-from-symbol-and-number -__Arg1 -__Arg2)
  (define (-__Func1)
    (let ((S -__Arg1)) (let ((N -__Arg2)) (<_> S N))))
  (-__Func1))
(define (my-gensym -__Arg1)
  (define (-__Func1)
    (let ((V -__Arg1))
      (begin
        (set! *my-gensym-N* (+ 1 *my-gensym-N*))
        (gensym-from-symbol-and-number V *my-gensym-N*))))
  (-__Func1))
(define (create-varlist)
  (define (-__Func1) '())
  (-__Func1))
(define (cons-varlist -__Arg1 -__Arg2 -__Arg3)
  (define (-__Func1)
    (let ((Var -__Arg1))
      (let ((Value -__Arg2))
        (let ((Varlist -__Arg3))
          `((,Var ,Value) ,@Varlist)))))
  (-__Func1))
(define (varlist-value -__Arg1 -__Arg2)
  (define (-__Func1)
    (if (null? -__Arg2)
      '-__not-in-varlist
      (-__Func2)))
  (define (-__Func2)
    (let ((A -__Arg1))
      (if (pair? -__Arg2)
        (let ((-__MatchCar1 (car -__Arg2))
              (-__MatchCdr2 (cdr -__Arg2)))
          (if (pair? -__MatchCar1)
            (let ((-__MatchCar3 (car -__MatchCar1))
                  (-__MatchCdr4 (cdr -__MatchCar1)))
              (if (equal? A -__MatchCar3)
                (if (pair? -__MatchCdr4)
                  (let ((-__MatchCar5 (car -__MatchCdr4))
                        (-__MatchCdr6 (cdr -__MatchCdr4)))
                    (let ((Value -__MatchCar5))
                      (if (null? -__MatchCdr6) Value (-__Func3))))
                  (-__Func3))
                (-__Func3)))
            (-__Func3)))
        (-__Func3))))
  (define (-__Func3)
    (let ((Var -__Arg1))
      (if (pair? -__Arg2)
        (let ((-__MatchCar7 (car -__Arg2))
              (-__MatchCdr8 (cdr -__Arg2)))
          (let ((V -__MatchCar7))
            (let ((Vs -__MatchCdr8)) (varlist-value Var Vs))))
        (error-no-match))))
  (-__Func1))
(define (transform-to-check-similarities-0
         -__Arg1
         -__Arg2
         -__Arg3
         -__Arg4)
  (define (-__Func1)
    (let ((R -__Arg1))
      (if (equal? R -__Arg3) R (-__Func2))))
  (define (-__Func2)
    (if (pair? -__Arg1)
      (let ((-__MatchCar1 (car -__Arg1))
            (-__MatchCdr2 (cdr -__Arg1)))
        (if (eqv? -__MatchCar1 'if)
          (if (pair? -__MatchCdr2)
            (let ((-__MatchCar3 (car -__MatchCdr2))
                  (-__MatchCdr4 (cdr -__MatchCdr2)))
              (let ((Test -__MatchCar3))
                (if (pair? -__MatchCdr4)
                  (let ((-__MatchCar5 (car -__MatchCdr4))
                        (-__MatchCdr6 (cdr -__MatchCdr4)))
                    (let ((Body -__MatchCar5))
                      (if (pair? -__MatchCdr6)
                        (let ((-__MatchCar7 (car -__MatchCdr6))
                              (-__MatchCdr8 (cdr -__MatchCdr6)))
                          (let ((F -__MatchCar7))
                            (if (null? -__MatchCdr8)
                              (if (equal? F -__Arg2)
                                (let ((R -__Arg3))
                                  (let ((Varlist -__Arg4))
                                    `(if ,Test
                                       ,(transform-to-check-similarities-0
                                          Body
                                          F
                                          R
                                          Varlist)
                                       ,F)))
                                (-__Func3))
                              (-__Func3))))
                        (-__Func3))))
                  (-__Func3))))
            (-__Func3))
          (-__Func3)))
      (-__Func3)))
  (define (-__Func3)
    (if (pair? -__Arg1)
      (let ((-__MatchCar9 (car -__Arg1))
            (-__MatchCdr10 (cdr -__Arg1)))
        (if (eqv? -__MatchCar9 'let)
          (if (pair? -__MatchCdr10)
            (let ((-__MatchCar11 (car -__MatchCdr10))
                  (-__MatchCdr12 (cdr -__MatchCdr10)))
              (if (pair? -__MatchCar11)
                (let ((-__MatchCar15 (car -__MatchCar11))
                      (-__MatchCdr16 (cdr -__MatchCar11)))
                  (if (pair? -__MatchCar15)
                    (let ((-__MatchCar17 (car -__MatchCar15))
                          (-__MatchCdr18 (cdr -__MatchCar15)))
                      (let ((Varname -__MatchCar17))
                        (if (pair? -__MatchCdr18)
                          (let ((-__MatchCar19 (car -__MatchCdr18))
                                (-__MatchCdr20 (cdr -__MatchCdr18)))
                            (let ((Value -__MatchCar19))
                              (if (null? -__MatchCdr20)
                                (if (null? -__MatchCdr16)
                                  (if (pair? -__MatchCdr12)
                                    (let ((-__MatchCar13 (car -__MatchCdr12))
                                          (-__MatchCdr14 (cdr -__MatchCdr12)))
                                      (let ((Body -__MatchCar13))
                                        (if (null? -__MatchCdr14)
                                          (let ((F -__Arg2))
                                            (let ((R -__Arg3))
                                              (let ((Varlist -__Arg4))
                                                (let ((Prev-value
                                                        (varlist-value
                                                          Varname
                                                          Varlist)))
                                                  (if (eq? Prev-value
                                                           '-__not-in-varlist)
                                                    `(let ((,Varname ,Value))
                                                       ,(transform-to-check-similarities-0
                                                          Body
                                                          F
                                                          R
                                                          (cons-varlist
                                                            Varname
                                                            Value
                                                            Varlist)))
                                                    `(if (equal?
                                                           ,Varname
                                                           ,Value)
                                                       ,(transform-to-check-similarities-0
                                                          Body
                                                          F
                                                          R
                                                          Varlist)
                                                       ,F))))))
                                          (-__Func4))))
                                    (-__Func4))
                                  (-__Func4))
                                (-__Func4))))
                          (-__Func4))))
                    (-__Func4)))
                (-__Func4)))
            (-__Func4))
          (-__Func4)))
      (-__Func4)))
  (define (-__Func4)
    (if (pair? -__Arg1)
      (let ((-__MatchCar21 (car -__Arg1))
            (-__MatchCdr22 (cdr -__Arg1)))
        (if (eqv? -__MatchCar21 'let)
          (if (pair? -__MatchCdr22)
            (let ((-__MatchCar23 (car -__MatchCdr22))
                  (-__MatchCdr24 (cdr -__MatchCdr22)))
              (let ((Vars -__MatchCar23))
                (if (pair? -__MatchCdr24)
                  (let ((-__MatchCar25 (car -__MatchCdr24))
                        (-__MatchCdr26 (cdr -__MatchCdr24)))
                    (let ((Body -__MatchCar25))
                      (if (null? -__MatchCdr26)
                        (let ((F -__Arg2))
                          (let ((R -__Arg3))
                            (let ((Varlist -__Arg4))
                              `(let ,Vars
                                 ,(transform-to-check-similarities-0
                                    Body
                                    F
                                    R
                                    Varlist)))))
                        (error-no-match))))
                  (error-no-match))))
            (error-no-match))
          (error-no-match)))
      (error-no-match)))
  (-__Func1))
(define (transform-to-check-similarities
         -__Arg1
         -__Arg2
         -__Arg3)
  (define (-__Func1)
    (let ((Body -__Arg1))
      (let ((Failure -__Arg2))
        (let ((Result -__Arg3))
          (transform-to-check-similarities-0
            Body
            Failure
            Result
            (create-varlist))))))
  (-__Func1))
(define (has-pipe -__Arg1)
  (define (-__Func1)
    (let ((M -__Arg1))
      (if (not (pair? M)) #f (-__Func2))))
  (define (-__Func2)
    (if (null? -__Arg1) #f (-__Func3)))
  (define (-__Func3)
    (let ((M -__Arg1))
      (if (eq? (car M) (string->symbol "|"))
        #t
        (-__Func4))))
  (define (-__Func4)
    (let ((M -__Arg1)) (has-pipe (cdr M))))
  (-__Func1))
(define (pipe-to-dot -__Arg1)
  (define (-__Func1)
    (if (null? -__Arg1) '() (-__Func2)))
  (define (-__Func2)
    (let ((M -__Arg1))
      (if (eq? (car M) (string->symbol "|"))
        (cadr M)
        (-__Func3))))
  (define (-__Func3)
    (let ((M -__Arg1))
      (cons (car M) (pipe-to-dot (cdr M)))))
  (-__Func1))
(define (create-single-matcher
         -__Arg1
         -__Arg2
         -__Arg3
         -__Arg4)
  (define (-__Func1)
    (if (null? -__Arg1)
      (if (null? -__Arg2)
        (let ((R -__Arg4)) R)
        (-__Func2))
      (-__Func2)))
  (define (-__Func2)
    (let ((I -__Arg1))
      (if (null? -__Arg2)
        (let ((F -__Arg3))
          (let ((R -__Arg4)) `(if (null? ,I) ,R ,F)))
        (-__Func3))))
  (define (-__Func3)
    (let ((Input-var -__Arg1))
      (let ((Matcher-var -__Arg2))
        (let ((F -__Arg3))
          (let ((R -__Arg4))
            (if (has-pipe Matcher-var)
              (create-single-matcher
                Input-var
                (pipe-to-dot Matcher-var)
                F
                R)
              (-__Func4)))))))
  (define (-__Func4)
    (let ((Input-var -__Arg1))
      (let ((Matcher-var -__Arg2))
        (let ((F -__Arg3))
          (let ((R -__Arg4))
            (if (pair? Matcher-var)
              (let* ((Car-var (my-gensym '-__MatchCar))
                     (Cdr-var (my-gensym '-__MatchCdr))
                     (Inner-Result
                       (create-single-matcher
                         Cdr-var
                         (cdr Matcher-var)
                         F
                         R))
                     (New-Result
                       (create-single-matcher
                         Car-var
                         (car Matcher-var)
                         F
                         Inner-Result)))
                `(if (pair? ,Input-var)
                   (let ((,Car-var (car ,Input-var))
                         (,Cdr-var (cdr ,Input-var)))
                     ,New-Result)
                   ,F))
              (-__Func5)))))))
  (define (-__Func5)
    (let ((Input-var -__Arg1))
      (let ((Matcher-var -__Arg2))
        (let ((F -__Arg3))
          (let ((R -__Arg4))
            (if (var? Matcher-var)
              `(let ((,Matcher-var ,Input-var)) ,R)
              (-__Func6)))))))
  (define (-__Func6)
    (let ((Input-var -__Arg1))
      (let ((Matcher-var -__Arg2))
        (let ((F -__Arg3))
          (let ((R -__Arg4))
            (if (and (symbol? Matcher-var)
                     (string=?
                       "_"
                       (substring (symbol->string Matcher-var) 0 1)))
              R
              (-__Func7)))))))
  (define (-__Func7)
    (let ((Input-var -__Arg1))
      (let ((Matcher-var -__Arg2))
        (let ((F -__Arg3))
          (let ((R -__Arg4))
            (if (scheme-symbol? Matcher-var)
              `(if (eqv? ,Input-var ',Matcher-var) ,R ,F)
              (-__Func8)))))))
  (define (-__Func8)
    (let ((Input-var -__Arg1))
      (let ((Matcher-var -__Arg2))
        (let ((F -__Arg3))
          (let ((R -__Arg4))
            `(if (eqv? ,Input-var ,Matcher-var) ,R ,F))))))
  (-__Func1))
(define (create-matcher-matcher-0
         -__Arg1
         -__Arg2
         -__Arg3
         -__Arg4)
  (define (-__Func1)
    (if (null? -__Arg1)
      (if (null? -__Arg2)
        (let ((Result -__Arg4)) Result)
        (-__Func2))
      (-__Func2)))
  (define (-__Func2)
    (if (pair? -__Arg1)
      (let ((-__MatchCar3 (car -__Arg1))
            (-__MatchCdr4 (cdr -__Arg1)))
        (let ((I -__MatchCar3))
          (let ((Is -__MatchCdr4))
            (if (pair? -__Arg2)
              (let ((-__MatchCar1 (car -__Arg2))
                    (-__MatchCdr2 (cdr -__Arg2)))
                (let ((M -__MatchCar1))
                  (let ((Ms -__MatchCdr2))
                    (let ((Failed -__Arg3))
                      (let ((Result -__Arg4))
                        (create-single-matcher
                          I
                          M
                          Failed
                          (create-matcher-matcher-0 Is Ms Failed Result)))))))
              (error-no-match)))))
      (error-no-match)))
  (-__Func1))
(define (create-matcher-matcher
         -__Arg1
         -__Arg2
         -__Arg3
         -__Arg4)
  (define (-__Func1)
    (let ((Inputs -__Arg1))
      (let ((Matchers -__Arg2))
        (let ((Failure -__Arg3))
          (let ((Result -__Arg4))
            (transform-to-check-similarities
              (create-matcher-matcher-0
                Inputs
                Matchers
                Failure
                Result)
              Failure
              Result))))))
  (-__Func1))
(define (list-split-0 -__Arg1 -__Arg2 -__Arg3 -__Arg4)
  (define (-__Func1)
    (let ((Before -__Arg1))
      (if (null? -__Arg2)
        (let ((Where -__Arg3))
          (let ((Func -__Arg4)) (Func Before '())))
        (-__Func2))))
  (define (-__Func2)
    (let ((Before -__Arg1))
      (if (pair? -__Arg2)
        (let ((-__MatchCar1 (car -__Arg2))
              (-__MatchCdr2 (cdr -__Arg2)))
          (let ((Where -__MatchCar1))
            (let ((After -__MatchCdr2))
              (if (equal? Where -__Arg3)
                (let ((Func -__Arg4)) (Func Before After))
                (-__Func3)))))
        (-__Func3))))
  (define (-__Func3)
    (let ((Before -__Arg1))
      (if (pair? -__Arg2)
        (let ((-__MatchCar3 (car -__Arg2))
              (-__MatchCdr4 (cdr -__Arg2)))
          (let ((A -__MatchCar3))
            (let ((After -__MatchCdr4))
              (let ((Where -__Arg3))
                (let ((Func -__Arg4))
                  (list-split-0
                    (append Before (list A))
                    After
                    Where
                    Func))))))
        (error-no-match))))
  (-__Func1))
(define (list-split -__Arg1 -__Arg2 -__Arg3)
  (define (-__Func1)
    (let ((All -__Arg1))
      (let ((Where -__Arg2))
        (let ((Func -__Arg3))
          (list-split-0 '() All Where Func)))))
  (-__Func1))
(define (get-matcher-where -__Arg1 -__Arg2)
  (define (-__Func1)
    (if (pair? -__Arg1)
      (let ((-__MatchCar1 (car -__Arg1))
            (-__MatchCdr2 (cdr -__Arg1)))
        (let ((Where -__MatchCar1))
          (if (pair? -__MatchCdr2)
            (let ((-__MatchCar3 (car -__MatchCdr2))
                  (-__MatchCdr4 (cdr -__MatchCdr2)))
              (let ((What -__MatchCar3))
                (let ((Rest -__MatchCdr4))
                  (let ((Kont -__Arg2))
                    (if (eqv? Where :where)
                      (Kont What Rest)
                      (-__Func2))))))
            (-__Func2))))
      (-__Func2)))
  (define (-__Func2)
    (let ((Rest -__Arg1))
      (let ((Kont -__Arg2)) (Kont '-__no_where Rest))))
  (-__Func1))
(define (get-matchers -__Arg1)
  (define (-__Func1)
    (if (null? -__Arg1) '() (-__Func2)))
  (define (-__Func2)
    (let ((All -__Arg1))
      (list-split
        All
        ':>
        (lambda (Before After)
          (let ((Result (car After)))
            (get-matcher-where
              (cdr After)
              (lambda (Where Rest)
                `((,Before ,Result ,Where) ,@(get-matchers Rest)))))))))
  (-__Func1))
(define (get-args -__Arg1)
  (define (-__Func1)
    (if (eqv? -__Arg1 0) '() (-__Func2)))
  (define (-__Func2)
    (let ((N -__Arg1))
      (append
        (get-args (- N 1))
        `(,(gensym-from-symbol-and-number '-__Arg N)))))
  (-__Func1))
(define (get-function-names -__Arg1)
  (define (-__Func1)
    (if (eqv? -__Arg1 0) '() (-__Func2)))
  (define (-__Func2)
    (let ((N -__Arg1))
      (append
        (get-function-names (- N 1))
        `((,(gensym-from-symbol-and-number '-__Func N))))))
  (-__Func1))
(define (make-local-func -__Arg1 -__Arg2)
  (define (-__Func1)
    (let ((Name -__Arg1))
      (let ((Body -__Arg2)) `(define ,Name ,Body))))
  (-__Func1))
(define (create-local-funcs-0 -__Arg1 -__Arg2 -__Arg3)
  (define (-__Func1)
    (if (null? -__Arg2)
      (if (pair? -__Arg3)
        (let ((-__MatchCar1 (car -__Arg3))
              (-__MatchCdr2 (cdr -__Arg3)))
          (let ((Error-func -__MatchCar1))
            (if (null? -__MatchCdr2) '() (-__Func2))))
        (-__Func2))
      (-__Func2)))
  (define (-__Func2)
    (let ((Is -__Arg1))
      (if (pair? -__Arg2)
        (let ((-__MatchCar7 (car -__Arg2))
              (-__MatchCdr8 (cdr -__Arg2)))
          (let ((M -__MatchCar7))
            (let ((Ms -__MatchCdr8))
              (if (pair? -__Arg3)
                (let ((-__MatchCar3 (car -__Arg3))
                      (-__MatchCdr4 (cdr -__Arg3)))
                  (let ((F1 -__MatchCar3))
                    (if (pair? -__MatchCdr4)
                      (let ((-__MatchCar5 (car -__MatchCdr4))
                            (-__MatchCdr6 (cdr -__MatchCdr4)))
                        (let ((F2 -__MatchCar5))
                          (let ((Fs -__MatchCdr6))
                            (let* ((Left-side (nth 1 M))
                                   (Right-side (nth 2 M))
                                   (Where (nth 3 M)))
                              `(,(make-local-func
                                   F1
                                   (create-matcher-matcher
                                     Is
                                     Left-side
                                     F2
                                     (if (eq? Where '-__no_where)
                                       Right-side
                                       `(if ,Where ,Right-side ,F2))))
                                ,@(create-local-funcs-0 Is Ms `(,F2 ,@Fs)))))))
                      (error-no-match))))
                (error-no-match)))))
        (error-no-match))))
  (-__Func1))
(define (create-local-funcs -__Arg1)
  (define (-__Func1)
    (let ((All -__Arg1))
      (let* ((Matchers (get-matchers All))
             (Args (get-args (length (car (car Matchers)))))
             (Function-names
               (append
                 (get-function-names (length Matchers))
                 `((error-no-match)))))
        (create-local-funcs-0
          Args
          Matchers
          Function-names))))
  (-__Func1))
(define (create-matcher-func -__Arg1 -__Arg2)
  (define (-__Func1)
    (let ((Name -__Arg1))
      (let ((Matchers -__Arg2))
        (let* ((Num-args
                 (list-split
                   Matchers
                   ':>
                   (lambda (Before After) (length Before))))
               (Args (get-args Num-args)))
          (append
            '(define)
            `((,Name ,@Args))
            (create-local-funcs Matchers)
            (get-function-names 1))))))
  (-__Func1))
